esphome:
	name: pyramidrgb-demo

esp32:
	board: esp32-s3-devkitc-1
	framework:
		type: esp-idf

logger:
	level: DEBUG

api:
ota:
wifi:
	ssid: "<YOUR_WIFI_SSID>"
	password: "<YOUR_WIFI_PASSWORD>"

external_components:
	- source: local

i2c:
	sda: GPIO38
	scl: GPIO39
	scan: true
	frequency: 400kHz

# Parent devices: per-strip config, including dimming and current mapping
pyramidrgb:
	- id: pyramid_rgb1
		strip: 1
		brightness: 100
		initial_white: 0

	- id: pyramid_rgb2
		strip: 2
		brightness: 100
		initial_white: 0

# Child outputs: map each channel + color, using the parent’s mapping
output:
	# Strip 1, Channel 0 (Group 1)
	- platform: pyramidrgb
		id: rgb1_ch0_red
		pyramidrgb_id: pyramid_rgb1
		channel: 0
		color: red
	- platform: pyramidrgb
		id: rgb1_ch0_green
		pyramidrgb_id: pyramid_rgb1
		channel: 0
		color: green
	- platform: pyramidrgb
		id: rgb1_ch0_blue
		pyramidrgb_id: pyramid_rgb1
		channel: 0
		color: blue

	# Strip 1, Channel 1 (Group 2)
	- platform: pyramidrgb
		id: rgb1_ch1_red
		pyramidrgb_id: pyramid_rgb1
		channel: 1
		color: red
	- platform: pyramidrgb
		id: rgb1_ch1_green
		pyramidrgb_id: pyramid_rgb1
		channel: 1
		color: green
	- platform: pyramidrgb
		id: rgb1_ch1_blue
		pyramidrgb_id: pyramid_rgb1
		channel: 1
		color: blue

	# Strip 2, Channel 2 (Group 1)
	- platform: pyramidrgb
		id: rgb2_ch2_red
		pyramidrgb_id: pyramid_rgb2
		channel: 2
		color: red
	- platform: pyramidrgb
		id: rgb2_ch2_green
		pyramidrgb_id: pyramid_rgb2
		channel: 2
		color: green
	- platform: pyramidrgb
		id: rgb2_ch2_blue
		pyramidrgb_id: pyramid_rgb2
		channel: 2
		color: blue

	# Strip 2, Channel 3 (Group 2)
	- platform: pyramidrgb
		id: rgb2_ch3_red
		pyramidrgb_id: pyramid_rgb2
		channel: 3
		color: red
	- platform: pyramidrgb
		id: rgb2_ch3_green
		pyramidrgb_id: pyramid_rgb2
		channel: 3
		color: green
	- platform: pyramidrgb
		id: rgb2_ch3_blue
		pyramidrgb_id: pyramid_rgb2
		channel: 3
		color: blue

# RGB lights combining outputs per group
light:
	- platform: rgb
		name: "Strip1 Group1"
		red: rgb1_ch0_red
		green: rgb1_ch0_green
		blue: rgb1_ch0_blue

	- platform: rgb
		name: "Strip1 Group2"
		red: rgb1_ch1_red
		green: rgb1_ch1_green
		blue: rgb1_ch1_blue

	- platform: rgb
		name: "Strip2 Group1"
		red: rgb2_ch2_red
		green: rgb2_ch2_green
		blue: rgb2_ch2_blue

	- platform: rgb
		name: "Strip2 Group2"
		red: rgb2_ch3_red
		green: rgb2_ch3_green
		blue: rgb2_ch3_blue
