esphome:
  name: switchc6-simple
  friendly_name: SwitchC6 Simple

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: VERBOSE

api:
  key: "X7+AfftIYMa/cDqk1pZ9dug7cas7U3/tg5zghRQ1Gow="

ota:
  - platform: esphome
    password: "1d25a8a9ad6d2069fd467f15c7795700"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Switch Fallback Hotspot"
    password: "TVP1qcPH6I64"

captive_portal:

espnow:
  id: espnow1
  auto_add_peer: true

switch:
  - platform: espnow_switch
    name: "SwitchC6 Device 1"
    espnow_id: espnow1
    mac_address: "B4:3A:45:81:EC:70"
    device_id: "142B-2F9F-8704"
    retry_count: 40         
    retry_interval: 100      
  
  - platform: espnow_switch
    name: "SwitchC6 Device 2"
    espnow_id: espnow1
    mac_address: "AA:BB:CC:DD:EE:FF"
    device_id: "1234-5678-9ABC"
    retry_count: 30
    retry_interval: 150
  