esphome:
  name: switchc6-simple
  friendly_name: SwitchC6 Simple

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: VERBOSE

api:
  encryption:
    key: "X7+AfftIYMa/cDqk1pZ9dug7cas7U3/tg5zghRQ1Gow="

ota:
  - platform: esphome
    password: "1d25a8a9ad6d2069fd467f15c7795700"

external_components:
  - source: github://Jasionf/echo-pyramid-components@main
    components: [espnow_switch]
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Switch Fallback Hotspot"
    password: "TVP1qcPH6I64"

captive_portal:


espnow:
  id: espnow1
  auto_add_peer: true
  on_broadcast:
    - lambda: |-
        // 将广播的数据传递给组件用于停止重试
        id(sw1).handle_broadcast(data, size);

switch:
  # 第一个 ESPNow 开关
  - platform: espnow_switch
    id: sw1
    name: "SwitchC6 Device 1"
    espnow_id: espnow1
    mac_address: "B4:3A:45:81:EC:70"
    response_token: "142B-2F9F-8704"
    retry_count: 12
    retry_interval: 300
  