esphome:
  name: unit-step16-full
  friendly_name: Unit Step16 Full Example

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your-encryption-key"

ota:
  - platform: esphome
    password: "your-ota-password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "Unit-Step16 Fallback Hotspot"
    password: "12345678"

captive_portal:

# I2C configuration
i2c:
  - id: bsp_iic
    scl: GPIO32
    sda: GPIO26
    scan: true

# Unit Step16 component
unit_step16:
  id: my_step16
  i2c_id: bsp_iic
  address: 0x48

# Sensor to read encoder value (0-15)
sensor:
  - platform: unit_step16
    unit_step16_id: my_step16
    name: "Encoder Value"
    update_interval: 100ms
    on_value:
      then:
        - logger.log:
            format: "Encoder value changed to: %.0f"
            args: [ 'x' ]

# Output components for LED and RGB control
output:
  # LED brightness control (0-100%)
  - platform: unit_step16
    id: led_brightness_output
    unit_step16_id: my_step16
    channel: led_brightness
  
  # RGB brightness control (0-100%)
  - platform: unit_step16
    id: rgb_brightness_output
    unit_step16_id: my_step16
    channel: rgb_brightness
  
  # RGB color channels (0-255 each)
  - platform: unit_step16
    id: rgb_red_output
    unit_step16_id: my_step16
    channel: rgb_red
  
  - platform: unit_step16
    id: rgb_green_output
    unit_step16_id: my_step16
    channel: rgb_green
  
  - platform: unit_step16
    id: rgb_blue_output
    unit_step16_id: my_step16
    channel: rgb_blue

# Create a light entity for RGB control
light:
  - platform: rgb
    name: "Step16 RGB Light"
    red: rgb_red_output
    green: rgb_green_output
    blue: rgb_blue_output
    # Optional: add effects
    effects:
      - pulse:
      - strobe:
      - random:

# Create a light entity for LED brightness (monochrome)
  - platform: monochromatic
    name: "Step16 LED Display"
    output: led_brightness_output
    # Optional: add effects
    effects:
      - pulse:
      - strobe:

# Optional: Control RGB brightness separately as a number
number:
  - platform: template
    name: "RGB Brightness"
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    initial_value: 50
    on_value:
      then:
        - output.set_level:
            id: rgb_brightness_output
            level: !lambda 'return x / 100.0;'

# Optional: Example automation - change RGB color based on encoder position
# This creates a color wheel effect
on_boot:
  - priority: -100
    then:
      - logger.log: "Unit Step16 initialized"
      # Turn on LED display
      - light.turn_on:
          id: step16_led_display
          brightness: 50%
      # Turn on RGB with initial color
      - light.turn_on:
          id: step16_rgb_light
          brightness: 50%
          red: 0%
          green: 100%
          blue: 0%
